# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 876f7b91f3999fb7b83e3b276082e2d20760a914dfbad19698768012fb2d1d525725b3aba4a34312e1866ed2bc51845304aa197f27a458831dd7e78f874efbaf

test:
  secret_key_base: d0fc3ff6ce2a1c6b516f30f2036ba96a5769e35c7640aeca98fb418dd523c0f9f4af97154e3afd8e5faa039a7f7dfcac68aa8903e7e43367d7966c5e632952f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
